### ISSUE TITLE
Is there a API available?

### ISSUE THREAD

**Issue by npomfret** [bitfinexcom/bfx-report-ui#221]
I'm looking for API access in order to download my full history.  The v1 and v2 rest APIs don't appear to return older trades for delisted symbols (like BCH/USD).  But I can see them in this new report ui.

Is it possible to get API access?

**Comment by ezeswci** [comment]
@npomfret we use bitfinex-api-node as to gather the information, can check the back-end code is in here: https://github.com/bitfinexcom/bfx-report
By the way not sure what you mean by 

> don't appear to return older trades for delisted symbols (like BCH/USD),

Just try `'tBCHUSD` in https://github.com/bitfinexcom/bfx-api-node-rest/blob/master/lib/rest2.js#L506 and works fine.

**Comment by npomfret** [comment]
@ezeswci thanks.  I didn't know what the symbol was (it's changed to tBAB...)

**Comment by npomfret** [comment]
@ezeswci do you know what API call is made to get the entire history of trades for all symbols (the only api call I can see involves using a symbol as a mandatory parameter)

**Comment by npomfret** [comment]
@ezeswci when I used the v2 api (`/v2/auth/r/trades/hist`  without a symbol) I only seem to get data going back a few months - most of it it missing.  Is there a trick to getting _older_ data out of the API?

**Comment by ezeswci** [comment]
Check the query params: https://docs.bitfinex.com/v2/reference 
There is a start, end and limit
